#!/usr/bin/env python

from os import listdir
from pathlib import Path

from interactive import load_router_peers, save_router_peers

routers = sorted([Path(router).stem for router in listdir('routers')])

for router in routers:
    peers = load_router_peers(router)
    save_router_peers(router, peers)
