name: Pull Request

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  dry_run:
    name: Validate
    uses: ./.github/workflows/validate.yml
    needs: [ lint ]
    secrets: inherit
